# Use this file as a template to create application-local.properties file to store your local db credentials
spring.datasource.url=${INVENTORY_DB_URL:jdbc:postgresql://inventory_db:5432/inventory_service}
spring.datasource.username=${INVENTORY_DB_USER:your_local_db_username_here}
spring.datasource.password=${INVENTORY_DB_PASS:your_local_db_password_here}